//! Isolated secret-material primitives.
//!
//! Rules for anything added to this crate:
//!   - no logging, no network, no file I/O
//!   - every type holding key material zeroizes on drop
//!   - Debug/Display on secret types must redact, never print raw bytes
//!   - randomness for key material comes only through `SecureRng`, which
//!     wraps the OS CSPRNG — never a seeded/deterministic RNG

use k256::Scalar;
use rand::rngs::OsRng;
use rand_core::{CryptoRng, RngCore};
use zeroize::{Zeroize, ZeroizeOnDrop};

pub mod keys;
pub mod shamir;

/// SHA-256 of `bytes`. Exposed so downstream crates (`wallet-core`, when
/// hashing a `wallet-decoder`-validated transaction before signing) don't
/// need their own hash-function dependency — reuses `k256`'s already-
/// present `sha2` re-export rather than pulling in a second copy.
pub fn sha256(bytes: &[u8]) -> [u8; 32] {
    use k256::sha2::{Digest, Sha256};
    Sha256::digest(bytes).into()
}

/// Keccak-256 of `bytes` — the pre-standardization Keccak padding Ethereum
/// uses, *not* NIST SHA3-256 (a different, incompatible padding scheme
/// despite the similar name). Needed for EVM addresses (keccak of the
/// uncompressed public key) and EIP-1559 transaction signing hashes.
pub fn keccak256(bytes: &[u8]) -> [u8; 32] {
    use sha3::{Digest, Keccak256};
    Keccak256::digest(bytes).into()
}

/// A fixed-size secret buffer that zeroizes on drop and never leaks its
/// contents through Debug/Display.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct SecretBytes<const N: usize>([u8; N]);

impl<const N: usize> SecretBytes<N> {
    /// The only constructor that draws from randomness. There is no
    /// seeded/deterministic path into a `SecretBytes`.
    pub fn random() -> Self {
        let mut buf = [0u8; N];
        SecureRng::new().fill(&mut buf);
        Self(buf)
    }

    /// Wrap already-generated bytes (e.g. decrypted from storage) as a
    /// `SecretBytes`, gaining its zeroize-on-drop/redacted-Debug behavior.
    pub fn from_array(bytes: [u8; N]) -> Self {
        Self(bytes)
    }

    /// Expose the bytes for direct use (e.g. handing to a signing routine).
    /// Callers must not copy this into a non-zeroizing buffer or log it.
    pub fn expose(&self) -> &[u8; N] {
        &self.0
    }
}

impl<const N: usize> std::fmt::Debug for SecretBytes<N> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SecretBytes<{N}>(REDACTED)")
    }
}

/// A secp256k1 scalar known to hold secret material — a private key, a
/// Shamir polynomial coefficient, a reconstructed/accumulated secret, and
/// so on. Zeroizes on drop automatically.
///
/// This exists so a secret-holding scalar can't be introduced as a bare
/// `k256::Scalar` local with no cleanup guarantee at all, which is
/// exactly the bug class a security audit caught in `shamir.rs`:
/// polynomial coefficients and a reconstructed secret sitting as plain
/// `Scalar` locals, wiped only if someone remembered to call `.zeroize()`
/// by hand — and one instance where that memory-holding didn't happen.
/// Wrapping the type makes cleanup automatic and impossible to forget,
/// the same way `SecretBytes`/`PrivateKey` already do for byte buffers
/// and the private key itself. `bytes_to_scalar` in `shamir.rs` is the
/// single choke point where raw bytes become a secret scalar in this
/// crate — returning `SecretScalar` there means every caller downstream
/// gets the guarantee without having to opt in.
///
/// Residual, accepted risk: arithmetic (`+`, `*`, ...) still has to
/// happen on the raw `k256::Scalar` obtained via `expose()`, since this
/// type deliberately doesn't implement arithmetic traits itself — so a
/// short-lived, unwrapped copy exists for the duration of one expression
/// or one accumulation loop. This is the same class of shadow-copy
/// limitation already documented on `PrivateKey` (construction
/// temporaries) — the guardrail here targets *long-lived, named* secret
/// locals that survive to a function's end, which is what the audited
/// bug actually was, not every transient register-scale copy.
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct SecretScalar(Scalar);

impl SecretScalar {
    /// Expose the raw scalar for one arithmetic expression. The result
    /// has no zeroize guarantee of its own — use it briefly, then either
    /// let it fall out of scope or immediately wrap the result back into
    /// a `SecretScalar`.
    pub fn expose(&self) -> Scalar {
        self.0
    }
}

impl From<Scalar> for SecretScalar {
    fn from(scalar: Scalar) -> Self {
        Self(scalar)
    }
}

impl std::fmt::Debug for SecretScalar {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SecretScalar(REDACTED)")
    }
}

/// The single audited entry point for cryptographic randomness in this
/// workspace. Every crate that needs randomness for key material should
/// depend on `wallet-crypto` and use this rather than picking its own RNG.
pub struct SecureRng(OsRng);

impl SecureRng {
    /// Construct the OS-backed CSPRNG wrapper. Cheap — `OsRng` holds no
    /// state, so there's no cost to creating a fresh one per call site.
    pub fn new() -> Self {
        Self(OsRng)
    }

    /// Fill `buf` with cryptographically secure random bytes.
    pub fn fill(&mut self, buf: &mut [u8]) {
        self.0.fill_bytes(buf);
    }
}

impl Default for SecureRng {
    fn default() -> Self {
        Self::new()
    }
}

// Implementing rand_core's traits directly (rather than making callers
// reach into `.0`) lets `SecureRng` be passed straight into k256/ecdsa APIs
// that require `CryptoRngCore`, so key generation never has a second RNG
// path to audit.
impl RngCore for SecureRng {
    fn next_u32(&mut self) -> u32 {
        self.0.next_u32()
    }

    fn next_u64(&mut self) -> u64 {
        self.0.next_u64()
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        self.0.fill_bytes(dest);
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
        self.0.try_fill_bytes(dest)?;
        Ok(())
    }
}

impl CryptoRng for SecureRng {}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test-only hex decoder so these known-vector tests don't need to add
    /// a `hex` crate dependency to this deliberately minimal crate.
    fn decode_hex_32(s: &str) -> [u8; 32] {
        assert_eq!(s.len(), 64, "expected a 32-byte hex vector");
        let mut out = [0u8; 32];
        for i in 0..32 {
            out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
        }
        out
    }

    #[test]
    fn keccak256_matches_known_ethereum_vector() {
        // keccak256("") — go-ethereum's well-known `EmptyCodeHash`
        // constant. Confirms we're using Keccak padding, not NIST-final
        // SHA3-256 (which hashes "" to a different value).
        let expected = decode_hex_32("c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470");
        assert_eq!(keccak256(b""), expected);
    }

    #[test]
    fn keccak256_of_abc() {
        // keccak256("abc"), a widely-published test vector.
        let expected = decode_hex_32("4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45");
        assert_eq!(keccak256(b"abc"), expected);
    }

    #[test]
    fn secret_bytes_debug_is_redacted() {
        let s = SecretBytes::<32>::random();
        assert_eq!(format!("{s:?}"), "SecretBytes<32>(REDACTED)");
    }

    #[test]
    fn random_is_not_all_zero() {
        // Statistically this can never fail for a real CSPRNG.
        let s = SecretBytes::<32>::random();
        assert_ne!(s.expose(), &[0u8; 32]);
    }

    #[test]
    fn two_random_draws_differ() {
        let a = SecretBytes::<32>::random();
        let b = SecretBytes::<32>::random();
        assert_ne!(a.expose(), b.expose());
    }
}
