//! Isolated secret-material primitives.
//!
//! Rules for anything added to this crate:
//!   - no logging, no network, no file I/O
//!   - every type holding key material zeroizes on drop
//!   - Debug/Display on secret types must redact, never print raw bytes
//!   - randomness for key material comes only through `SecureRng`, which
//!     wraps the OS CSPRNG — never a seeded/deterministic RNG

use rand::rngs::OsRng;
use rand_core::{CryptoRng, RngCore};
use zeroize::{Zeroize, ZeroizeOnDrop};

pub mod keys;

/// A fixed-size secret buffer that zeroizes on drop and never leaks its
/// contents through Debug/Display.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct SecretBytes<const N: usize>([u8; N]);

impl<const N: usize> SecretBytes<N> {
    /// The only constructor that draws from randomness. There is no
    /// seeded/deterministic path into a `SecretBytes`.
    pub fn random() -> Self {
        let mut buf = [0u8; N];
        SecureRng::new().fill(&mut buf);
        Self(buf)
    }

    /// Wrap already-generated bytes (e.g. decrypted from storage) as a
    /// `SecretBytes`, gaining its zeroize-on-drop/redacted-Debug behavior.
    pub fn from_array(bytes: [u8; N]) -> Self {
        Self(bytes)
    }

    /// Expose the bytes for direct use (e.g. handing to a signing routine).
    /// Callers must not copy this into a non-zeroizing buffer or log it.
    pub fn expose(&self) -> &[u8; N] {
        &self.0
    }
}

impl<const N: usize> std::fmt::Debug for SecretBytes<N> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SecretBytes<{N}>(REDACTED)")
    }
}

/// The single audited entry point for cryptographic randomness in this
/// workspace. Every crate that needs randomness for key material should
/// depend on `wallet-crypto` and use this rather than picking its own RNG.
pub struct SecureRng(OsRng);

impl SecureRng {
    /// Construct the OS-backed CSPRNG wrapper. Cheap — `OsRng` holds no
    /// state, so there's no cost to creating a fresh one per call site.
    pub fn new() -> Self {
        Self(OsRng)
    }

    /// Fill `buf` with cryptographically secure random bytes.
    pub fn fill(&mut self, buf: &mut [u8]) {
        self.0.fill_bytes(buf);
    }
}

impl Default for SecureRng {
    fn default() -> Self {
        Self::new()
    }
}

// Implementing rand_core's traits directly (rather than making callers
// reach into `.0`) lets `SecureRng` be passed straight into k256/ecdsa APIs
// that require `CryptoRngCore`, so key generation never has a second RNG
// path to audit.
impl RngCore for SecureRng {
    fn next_u32(&mut self) -> u32 {
        self.0.next_u32()
    }

    fn next_u64(&mut self) -> u64 {
        self.0.next_u64()
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        self.0.fill_bytes(dest);
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
        self.0.try_fill_bytes(dest)?;
        Ok(())
    }
}

impl CryptoRng for SecureRng {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn secret_bytes_debug_is_redacted() {
        let s = SecretBytes::<32>::random();
        assert_eq!(format!("{s:?}"), "SecretBytes<32>(REDACTED)");
    }

    #[test]
    fn random_is_not_all_zero() {
        // Statistically this can never fail for a real CSPRNG.
        let s = SecretBytes::<32>::random();
        assert_ne!(s.expose(), &[0u8; 32]);
    }

    #[test]
    fn two_random_draws_differ() {
        let a = SecretBytes::<32>::random();
        let b = SecretBytes::<32>::random();
        assert_ne!(a.expose(), b.expose());
    }
}
